import type { Site } from "./types"

export const sitesData: Site[] = [
  {
    slug: "petra",
    name: "Petra",
    latitude: 30.3285,
    longitude: 35.4444,
    cover_image: "/petra-jordan.png",
    blurb: "Ancient city carved into sandstone cliffs in Jordan, famous for Al-Khazneh (The Treasury).",
    fullDescription:
      "Petra, a historical and archaeological city in southern Jordan, is famous for its rock-cut architecture and water conduit system. Established possibly as early as 312 BC as the capital city of the Arab Nabataeans, it is a symbol of Jordan, as well as its most-visited tourist attraction.",
    country: "Jordan",
    specificLocation: "Ma'an Governorate",
    primaryCategory: "Ancient Ruins",
    categories: ["ancient_ruins", "rock_cut_architecture"],
    continent: "asia",
    period: "c. 312 BC - AD 106",
    type: "Rock-cut City",
    unesco: true,
    media: [
      {
        src: "/petra-treasury-jordan.png",
        alt: "The Treasury at Petra",
        caption: "Al-Khazneh, The Treasury at Petra",
        type: "image",
      },
      {
        src: "/images/petra-monastery.png",
        alt: "The Monastery at Petra",
        caption: "Ad Deir, The Monastery, Petra",
        type: "image",
      },
      {
        src: "/images/petra-siq.png",
        alt: "The Siq, entrance to Petra",
        caption: "The Siq, the main entrance to Petra",
        type: "image",
      },
    ],
    tags: ["Nabataean", "UNESCO", "Desert City", "Archaeology"],
    article_url: "/sites/petra",
    location: {
      name: "Petra Visitor Center",
      address: "Petra Visitor Center, Wadi Musa, Jordan",
      coordinates: [30.3285, 35.4444],
      website: "https://www.visitpetra.jo",
      directionsUrl: "https://maps.google.com/?q=Petra,Jordan",
    },
    rating: 4.8,
    significance:
      "Major caravan city of the Nabataeans, known for its elaborate tombs and temples carved into pink sandstone cliffs.",
    visitors: "Over 1 million annually (pre-COVID)",
  },
  {
    slug: "machu-picchu",
    name: "Machu Picchu",
    latitude: -13.1631,
    longitude: -72.545,
    cover_image: "/machu-picchu-mountains.png",
    blurb: "15th-century Inca citadel set high in the Andes Mountains in Peru.",
    fullDescription:
      "Machu Picchu is an Incan citadel set high in the Andes Mountains in Peru, above the Urubamba River valley. Built in the 15th century and later abandoned, it’s renowned for its sophisticated dry-stone walls that fuse huge blocks without the use of mortar, intriguing buildings that play on astronomical alignments and panoramic views.",
    country: "Peru",
    specificLocation: "Cusco Region",
    primaryCategory: "Ancient Ruins",
    categories: ["ancient_ruins", "inca_civilization"],
    continent: "south_america",
    period: "c. AD 1450",
    type: "Inca Citadel",
    unesco: true,
    media: [
      {
        src: "/machu-picchu-overview.png",
        alt: "Overview of Machu Picchu",
        caption: "Panoramic view of the Inca citadel of Machu Picchu",
        type: "image",
      },
    ],
    tags: ["Inca", "UNESCO", "Andes Mountains", "Citadel"],
    article_url: "/sites/machu-picchu",
    location: {
      name: "Machu Picchu Archaeological Park",
      address: "Machu Picchu, Cusco Region, Peru",
      coordinates: [-13.1631, -72.545],
      website: "https://www.machupicchu.gob.pe/",
      directionsUrl: "https://maps.google.com/?q=Machu+Picchu,Peru",
    },
    rating: 4.9,
    significance:
      "Iconic Inca citadel, one of the New Seven Wonders of the World, known for its astronomical alignments and sophisticated architecture.",
    visitors: "Approx. 1.5 million annually (pre-COVID)",
  },
  {
    slug: "lascaux-cave",
    name: "Lascaux Cave",
    latitude: 45.0495,
    longitude: 1.1725,
    cover_image: "/lascaux-cave-paintings.png",
    blurb: "Complex of caves in southwestern France famous for its Paleolithic cave paintings.",
    fullDescription:
      "Lascaux is a network of caves near the village of Montignac, in the department of Dordogne in southwestern France. Over 600 parietal wall paintings cover the interior walls and ceilings of the cave. The paintings are primarily of large animals, typical local and contemporary fauna that correspond with the fossil record of the Upper Paleolithic in the area. They are the combined effort of many generations and, with continued debate, the age of the paintings is now usually estimated at around 17,000 years (early Magdalenian).",
    country: "France",
    specificLocation: "Nouvelle-Aquitaine",
    primaryCategory: "Rock Art",
    categories: ["rock_art", "paleolithic_art", "ancient_sites"],
    continent: "europe",
    period: "c. 17,000 BP",
    type: "Cave Paintings",
    unesco: true,
    media: [
      {
        src: "/placeholder.svg?height=800&width=1200",
        alt: "Detailed cave painting from Lascaux",
        caption: "Aurochs and horses depicted in Lascaux Cave",
        type: "image",
      },
    ],
    tags: ["Paleolithic", "UNESCO", "Cave Art", "Prehistory"],
    article_url: "/sites/lascaux-cave",
    location: {
      name: "Lascaux IV International Centre for Cave Art",
      address: "Lascaux IV, 24290 Montignac, France",
      coordinates: [45.0539, 1.1789], // Coordinates for Lascaux IV
      website: "https://www.lascaux.fr",
      directionsUrl: "https://maps.google.com/?q=Lascaux+IV",
    },
    rating: 4.7,
    significance:
      "Contains some of the most outstanding Paleolithic art, crucial for understanding early human artistic expression.",
    visitors: "Lascaux IV (replica) receives hundreds of thousands annually.",
  },
  {
    slug: "carnac-stones",
    name: "Carnac Stones",
    latitude: 47.5925,
    longitude: -3.0815,
    cover_image: "/placeholder.svg?height=400&width=500",
    blurb: "Exceptionally dense collection of megalithic sites in Brittany, France.",
    fullDescription:
      "The Carnac stones are an exceptionally dense collection of megalithic sites in Brittany in northwestern France, consisting of stone alignments (rows), dolmens (stone tombs), tumuli (burial mounds) and single menhirs (standing stones). More than 3,000 prehistoric standing stones were hewn from local granite and erected by the pre-Celtic people of Brittany, and are the largest such collection in the world.",
    country: "France",
    specificLocation: "Brittany",
    primaryCategory: "Megaliths",
    categories: ["megaliths", "neolithic", "ancient_sites"],
    continent: "europe",
    period: "c. 4500 BC - 3300 BC",
    type: "Megalithic Alignments",
    media: [
      {
        src: "/placeholder.svg?height=800&width=1200",
        alt: "Rows of Carnac Stones",
        caption: "The extensive alignments of the Carnac Stones",
        type: "image",
      },
    ],
    tags: ["Neolithic", "Standing Stones", "Prehistory", "Ritual Site"],
    article_url: "/sites/carnac-stones",
    location: {
      name: "Maison des Mégalithes",
      address: "Route de Kerlescan, D196, 56340 Carnac, France",
      coordinates: [47.5925, -3.0815],
      website: "http://www.menhirs-carnac.fr/",
      directionsUrl: "https://maps.google.com/?q=Carnac+Stones",
    },
    rating: 4.5,
    significance:
      "World's largest collection of megalithic alignments, offering insights into Neolithic European cultures.",
    visitors: "Significant tourist interest, specific numbers vary.",
  },
  {
    slug: "nazca-lines",
    name: "Nazca Lines",
    latitude: -14.739,
    longitude: -75.13,
    cover_image: "/placeholder.svg?height=400&width=600",
    blurb: "Series of large ancient geoglyphs in the Nazca Desert, in southern Peru.",
    fullDescription:
      "The Nazca Lines are a group of very large geoglyphs made in the soil of the Nazca Desert in southern Peru. They were created between 500 BCE and 500 CE by people making depressions or shallow incisions in the desert floor, removing pebbles and leaving differently colored dirt exposed. Most lines run straight across the landscape, but there are also figurative designs of animals and plants.",
    country: "Peru",
    specificLocation: "Nazca Desert",
    primaryCategory: "Geoglyphs",
    categories: ["geoglyphs", "unusual_formations", "ancient_sites"],
    continent: "south_america",
    period: "500 BCE - 500 CE",
    type: "Geoglyphs",
    unesco: true,
    media: [
      {
        src: "/placeholder.svg?height=800&width=1200",
        alt: "Aerial view of a Nazca Line figure",
        caption: "The Hummingbird geoglyph, Nazca Lines",
        type: "image",
      },
    ],
    tags: ["Nazca Culture", "UNESCO", "Desert Art", "Archaeology"],
    article_url: "/sites/nazca-lines",
    location: {
      name: "Nazca Lines Observation Tower",
      address: "Panamericana Sur km 424, Nazca, Peru",
      coordinates: [-14.7008, -75.1119], // Approx. for a viewing tower
      website: "https://www.nascaflights.com/",
      directionsUrl: "https://maps.google.com/?q=Nazca+Lines+Observation+Tower",
    },
    rating: 4.6,
    significance: "Enigmatic large-scale geoglyphs whose purpose is still debated, best viewed from the air.",
    visitors: "Popular for aerial tours.",
  },
  {
    slug: "pyramids-of-giza",
    name: "Pyramids of Giza",
    latitude: 29.9792,
    longitude: 31.1342,
    cover_image: "/placeholder.svg?height=400&width=600",
    blurb: "Iconic ancient Egyptian pyramids, including the Great Pyramid of Khufu.",
    fullDescription:
      "The Giza pyramid complex, on the outskirts of Cairo, Egypt, is home to the Great Pyramid of Giza, Pyramid of Khafre, and Pyramid of Menkaure, along with the Great Sphinx. These structures, built during the Fourth Dynasty of the Old Kingdom, are among the most famous and oldest surviving monuments in the world.",
    country: "Egypt",
    specificLocation: "Giza Plateau",
    primaryCategory: "Ancient Monuments",
    categories: ["ancient_monuments", "pyramids", "world_wonders"],
    continent: "africa",
    period: "c. 2589–2504 BC",
    type: "Pyramid Complex",
    unesco: true,
    media: [
      {
        src: "/placeholder.svg?height=800&width=1200",
        alt: "Pyramids of Giza overview",
        caption: "The Giza pyramid complex",
        type: "image",
      },
      {
        src: "/placeholder.svg?height=800&width=1200",
        alt: "The Great Sphinx of Giza",
        caption: "The Great Sphinx with pyramids in the background",
        type: "image",
      },
    ],
    tags: ["Ancient Egypt", "Pharaohs", "Tombs", "Archaeology", "UNESCO"],
    article_url: "/sites/pyramids-of-giza",
    location: {
      name: "Giza Necropolis",
      address: "Al Haram, Giza Governorate, Egypt",
      coordinates: [29.9792, 31.1342],
      website: "https://egymonuments.gov.eg/",
      directionsUrl: "https://maps.google.com/?q=Pyramids+of+Giza",
    },
    rating: 4.9,
    significance:
      "The last remaining of the Seven Wonders of the Ancient World, testament to ancient Egyptian engineering and beliefs.",
    visitors: "Approx. 14.7 million annually (pre-COVID)",
  },
]
