INSERT INTO public.sites (
    slug, name, latitude, longitude, cover_image, blurb, fullDescription, country, specificLocation, primaryCategory, categories, continent, period, type, unesco, tags, media, location
) VALUES
(
    'cahokia-mounds',
    'Cahokia Mounds',
    38.6563,
    -90.0618,
    '/placeholder.svg?height=400&width=600',
    'The largest pre-Columbian settlement north of Mexico, near modern-day St. Louis.',
    'Cahokia Mounds State Historic Site is the site of a pre-Columbian Native American city that existed from c. 1050–1350 CE across the Mississippi River from modern St. Louis, Missouri. This historical park lies in southern Illinois between East St. Louis and Collinsville. The park covers 2,200 acres, or about 3.5 square miles, and contains about 80 human-made mounds, but the ancient city was much larger. At its apex around 1100 CE, the city of Cahokia covered about 6 square miles and included about 120 earthworks in a wide range of sizes, shapes, and functions. Cahokia was the largest and most influential urban settlement of the Mississippian culture, which developed advanced societies across much of what is now the central and southeastern United States, beginning more than 1,000 years before European contact. Its population at its peak in the 12th century, an estimated 10,000 to 20,000 people, would not be surpassed by any city in the future United States until the 18th century.',
    'USA',
    'Illinois',
    'Ancient City',
    '{"ancient_city", "mississippian_culture", "earthworks"}',
    'north_america',
    'c. 1050–1350 CE',
    'Mound Complex',
    true,
    '{"Mississippian", "UNESCO", "Archaeology", "Native American"}',
    '[{"src": "/placeholder.svg?height=800&width=1200", "alt": "Monks Mound at Cahokia", "caption": "Monks Mound is the largest prehistoric earthwork in the Americas."}]',
    '{"name": "Cahokia Mounds State Historic Site", "address": "30 Ramey St, Collinsville, IL 62234, USA"}'
),
(
    'mesa-verde',
    'Mesa Verde',
    37.1838,
    -108.4887,
    '/placeholder.svg?height=400&width=600',
    'Home to the Ancestral Pueblo people, famous for its well-preserved cliff dwellings.',
    'Mesa Verde National Park is an American national park and UNESCO World Heritage Site located in Montezuma County, Colorado. The park protects some of the best-preserved Ancestral Puebloan archaeological sites in the United States. Created by President Theodore Roosevelt in 1906, the park occupies 52,485 acres near the Four Corners region. With more than 5,000 sites, including 600 cliff dwellings, it is the largest archaeological preserve in the US. Mesa Verde is best known for structures such as Cliff Palace, thought to be the largest cliff dwelling in North America. The Ancestral Pueblo people made Mesa Verde their home for over 700 years, from 600 to 1300 CE. The cliff dwellings were built in the last 100 years of this period. These structures, built within cliff alcoves, are some of the most notable and best-preserved in the North American continent. The reason for their sudden departure in the late 1200s remains a mystery.',
    'USA',
    'Colorado',
    'Cliff Dwellings',
    '{"cliff_dwellings", "ancient_ruins", "ancestral_puebloan"}',
    'north_america',
    'c. 600–1300 CE',
    'Archaeological Park',
    true,
    '{"Ancestral Puebloan", "UNESCO", "National Park", "Archaeology"}',
    '[{"src": "/placeholder.svg?height=800&width=1200", "alt": "View of Cliff Palace", "caption": "The impressive Cliff Palace at Mesa Verde National Park."}]',
    '{"name": "Mesa Verde National Park", "address": "Mesa Verde National Park, CO 81330, USA"}'
),
(
    'serra-da-capivara',
    'Serra da Capivara',
    -8.6667,
    -42.5500,
    '/placeholder.svg?height=400&width=600',
    'A national park in Brazil, home to the oldest prehistoric rock paintings in the Americas.',
    'Serra da Capivara National Park is a national park in the Northeast of Brazil. The park was created to protect the prehistoric artifacts and paintings found there. It has the largest and the oldest concentration of prehistoric sites in the Americas. Scientific studies confirm that the Capivara mountain range was densely populated in prehistoric periods. The park is rich in evidence of early human presence, with rock shelters decorated with rock paintings that represent scenes of hunting, dancing, and rituals. Some archaeologists believe the oldest paintings could be up to 50,000 years old, which challenges the long-held theory of when the Americas were first settled. The park contains over 1,300 archaeological sites, the majority of which are rock art panels. The art is remarkably well-preserved due to the dry climate. It provides a unique testimony to the life of some of the earliest human communities in South America.',
    'Brazil',
    'Piauí',
    'Rock Art',
    '{"rock_art", "paleolithic_art", "prehistoric_sites"}',
    'south_america',
    'c. 50,000–30,000 BP',
    'National Park',
    true,
    '{"Prehistoric", "UNESCO", "Cave Art", "Archaeology"}',
    '[{"src": "/placeholder.svg?height=800&width=1200", "alt": "Rock art at Serra da Capivara", "caption": "Prehistoric paintings depicting local fauna and human activities."}]',
    '{"name": "Serra da Capivara National Park", "address": "São Raimundo Nonato, Piauí, Brazil"}'
),
(
    'great-zimbabwe',
    'Great Zimbabwe',
    -20.2667,
    30.9333,
    '/placeholder.svg?height=400&width=600',
    'The ruins of a massive stone city, capital of the Kingdom of Zimbabwe during the Late Iron Age.',
    'Great Zimbabwe is a ruined city in the south-eastern hills of Zimbabwe near Lake Mutirikwe and the town of Masvingo. It was the capital of the Kingdom of Zimbabwe during the country''s Late Iron Age. Construction on the monument by ancestors of the Shona people began in the 11th century and continued until the 15th century. The stone city spans an area of 7.22 square kilometres which, at its peak, could have housed up to 18,000 people. It is recognized as a World Heritage Site by UNESCO. The ruins at Great Zimbabwe are some of the oldest and largest structures located in Southern Africa. The most formidable edifice, commonly referred to as the Great Enclosure, has walls as high as 11 metres extending approximately 250 metres, making it the largest ancient structure south of the Sahara Desert. The city was a major trading hub, with artifacts found from as far away as China, demonstrating its extensive commercial network.',
    'Zimbabwe',
    'Masvingo Province',
    'Ancient City',
    '{"ancient_city", "iron_age", "stone_architecture"}',
    'africa',
    'c. 11th–15th c. CE',
    'Stone Ruins',
    true,
    '{"Shona", "UNESCO", "Iron Age", "Trade Hub"}',
    '[{"src": "/placeholder.svg?height=800&width=1200", "alt": "The Great Enclosure at Great Zimbabwe", "caption": "The massive walls of the Great Enclosure."}]',
    '{"name": "Great Zimbabwe Ruins", "address": "Masvingo, Zimbabwe"}'
),
(
    'lalibela',
    'Lalibela',
    12.0319,
    39.0425,
    '/placeholder.svg?height=400&width=600',
    'A town in Ethiopia famous for its monolithic rock-hewn churches.',
    'Lalibela is a town in the Amhara Region of Ethiopia, famous for its monolithic rock-hewn churches. The whole of Lalibela is a large antiquity of the medieval and post-medieval civilization of Ethiopia. Lalibela is one of Ethiopia''s holiest cities, second only to Aksum, and a center of pilgrimage. Unlike Aksum, the population of Lalibela is almost completely Ethiopian Orthodox Christian. The layout and names of the major buildings in Lalibela are widely accepted, especially by local clergy, to be a symbolic representation of Jerusalem. This has led some experts to date the current church forms to the years following the capture of Jerusalem in 1187 by Muslim leader Saladin. The most famous of the churches is the cross-shaped Church of St. George (Bete Giyorgis). Tradition credits its construction to King Gebre Mesqel Lalibela of the Zagwe dynasty, who sought to recreate a New Jerusalem as his capital due to the historical importance of the city as a pilgrimage site.',
    'Ethiopia',
    'Amhara Region',
    'Religious Site',
    '{"religious_site", "rock_cut_architecture", "christianity"}',
    'africa',
    'c. 12th–13th c. CE',
    'Monolithic Churches',
    true,
    '{"Orthodox", "UNESCO", "Pilgrimage", "Rock-hewn"}',
    '[{"src": "/placeholder.svg?height=800&width=1200", "alt": "Church of St. George, Lalibela", "caption": "The iconic cross-shaped Bete Giyorgis (Church of St. George)."}]',
    '{"name": "Rock-Hewn Churches, Lalibela", "address": "Lalibela, Ethiopia"}'
);
